[package]
name = "guessing_game_error_handling"
version = "0.1.0"
authors = ["Florian GOTO <you@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"